config/routes.rb
Rails.application.routes.draw do
  get 'notices/new'
  get 'notices/index'
  get 'notices/edit'
  get 'notices/show'
  root to: "homes#home"
  get "/trimming" => "homes#trimming"
  get "/hotel" => "homes#hotel"
  get "/information" => "homes#information"
  
  resources :docotrs, only: [:index] 
  devise_for :doctors  ,controllers: {
    sessions: 'doctors/sessions'
  }
  
  resources :notices
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :notices
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/notice.rb
class Notice < ApplicationRecord
   belongs_to :category
   mount_uploaders :images, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors/categories_controller.rb
class Doctors::CategoriesController < ApplicationController
  
  def index
    @categories = Category.all
    @category = Category.new
    
    
  end  
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to doctors_categories_path
    else
      render "index"
    end  
  end
  
  def edit
  end  
  
  def update
  end
  
  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to doctors_categories_path
    else 
      render "index"
    end  
  end
  
  private
  # def set_category
  #   @category = Category.find(params[:id])
  # end

  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/doctors/confirmations_controller.rb
# frozen_string_literal: true

class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/notices_controller.rb
class Doctors::NoticesController < ApplicationController
  
  def index
    @notices = Notice.all
    # @category = notice.category
    
  end
  def show
    @notice = Notice.find(params[:id])
    @category = Category.find(params[:id])
  end 
  
  def new
    @notice = Notice.new
  end
  
  def create
    @notice = Notice.new(notice_params)
    @notice.doctor_id = current_doctor.id
    if @notice.save
      redirect_to doctors_notice_path(@notice.id)
    else
      render "new"
    end  
  end
  
  def edit
    @notice = Notice.find(params[:id])
  end
  
  def update
    @notice = Notice.find(params[:id])
    if  @notice.update
     redirect_to doctors_notice_path(@notice.id)
    else  
      "edit"
    end  
  end
  
  def destroy
    @notice = Notice.find(params[:id])
    if @notice.destroy
      redirect_to doctors_notices_path
    else
      render "show"
    end  
  end
  
  private
  
  def notice_params
  # params.require(:notice).permit(:title, :body, :category_id, :doctor_id)
  params.permit(:title, :body, :category_id, :doctor_id)
  end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
# frozen_string_literal: true

class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
# frozen_string_literal: true

class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
    @notice = Notice.first(5)
  end
  
  def trimming
  end
  
  def hotel
  end
  
  def information
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def new
    @notice = Notice.new
  end
  
  def create
    @notice = Notice.new(notice_params)
    @notice.save
    redirect_to notice_path(@notice.id)
  end

  def index
    @notices = Notice.all
  end

  def edit
    @notice = Notice.find(params[:id])
  end
  
  def update 
    @notice = Notice.find(params[:id])
    @notice.update(notice_params)
    redirect_to notice_path(@notice.id)
  end
  def show
    @notice = Notice.find(params[:id])
  end
  
  private 
  
  def notice_params
    params.require(:notice).permit(:title, :body, :category_id, { images: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/categories/edit.html.erb
<div class="flame-top"></div>
<h1>カテゴリー編集画面</h1>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    <div class="box">
      <%= form_with model: @category, local: true do |f| %>
        <%= f.label :name, "カテゴリー名" %>
        <%= f.text_field :name %>
        <%= f.submit "保存" %>
      <% end %>
    </div>
  </div>
  <div class="sidebar-right"></div>
</div>

app/views/categories/index.html.erb
<div class="flame-top"></div>
<h1>記事投稿画面</h1>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    <div class="box">
      <%= form_with model: @category, local: true do |f| %>
        <table>
          <tr>
            <td><%= f.label :name, "カテゴリー名" %></td>
          </tr>
          <tr>
            <td><%= f.text_field :name %></td>
          </tr>
        </table><br />
        <%= f.submit "投稿" %>
      <% end %>
    </div>
    <div class="box">
      <table>
        <thead>
          <tr>
            <th>カテゴリー名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td>
              <%= category.name %>
            </td>
            <td>
              <%= link_to "編集", edit_category_path(category.id) %>
              <%= link_to "削除", category_path(category.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="sidebar-right"></div>
</div>

app/views/doctors/notices/edit.html.erb
<div class="flame-top"></div>
<h1>記事編集画面</h1>
<div class="containers">
  <div class="sidebar-left"></div>
    <div class="main-container">
      <div class="box">
        <%= form_with url: doctors_notices_path, local: true do |f| %>
          <table>
            <tr>
              <td><%= f.label :title, "タイトル" %></td>
            </tr>
            <tr>
              <td><%= f.text_field :title %></td>
            </tr>
            <tr>
              <td><%= f.label :body, "テキスト" %></td>
            </tr>
            <tr>
              <td><%= f.text_area :body %></td>
            </tr>
            <tr>
              <td><%= f.label :category, "カテゴリ" %></td>
            </tr>
            <tr>
              <td><%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "--選択してください--"} %></td>
            </tr>
          </table><br />
          <%= f.submit "投稿" %>
        <% end %>
      </div>
    </div>
    <div class="sidebar-right"></div>
  </div>
</div>

app/views/doctors/notices/index.html.erb
<div class="flame-top"></div>
<h1>投稿記事一覧</h1>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    <div class="box">
      <table>
        <thead>
          <tr>
            <th>タイトル</th>
            <th>テキスト</th>
            <th>カテゴリ</th>
            <th></th>
          </tr>  
        </thead>
        <tbody>
          <% @notices.each do |notice| %>
            <tr>
              <td>
                <%= notice.title %>
              </td>
              <td>
                <%= notice.body %>
              </td>
              <td><%= notice.category_id %></td>
              <td>
                <%= link_to "編集", edit_doctors_notice_path(notice.id) %> 
                <%= link_to "削除", doctors_notice_path(notice.id), method: :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
   <div class="sidebar-right"></div>
</div>
  

app/views/doctors/notices/new.html.erb
<div class="flame-top"></div>
<h1>記事投稿画面</h1>
<div class="containers">
  <div class="sidebar-left"></div>
    <div class="main-container">
      <div class="box">
        <%= form_with url: doctors_notices_path, local: true do |f| %>
          <table>
            <tr>
              <td><%= f.label :title, "タイトル" %></td>
            </tr>
            <tr>
              <td><%= f.text_field :title %></td>
            </tr>
            <tr>
              <td><%= f.label :body, "テキスト" %></td>
            </tr>
            <tr>
              <td><%= f.text_area :body %></td>
            </tr>
            <tr>
              <td><%= f.label :category, "カテゴリ" %></td>
            </tr>
            <tr>
              <td><%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "--選択してください--"} %></td>
            </tr>
          </table><br />
          <%= f.submit "投稿" %>
        <% end %>
      </div>
    </div>
    <div class="sidebar-right"></div>
  </div>
</div>

app/views/doctors/notices/show.html.erb
<div class="flame-top"></div>
<h1>記事投稿 確認画面</h1>
<div class="containers">
  <div class="sidebar-left"></div>
    <div class="main-container">
      <div class="box">
          <table>
            <tr>
              <th>タイトル</th>
            </tr>
            <tr>
              <td><%= @notice.title %></td>
            </tr>
            <tr>
              <th>テキスト</th>
            </tr>
            <tr>
              <td><%= @notice.body %></td>
            </tr>
            <tr>
              <th>カテゴリ</th>
            </tr>
            <tr>
              <td><%= @category.name %></td>
            </tr>
          </table><br />
          <%= link_to "編集", edit_doctors_notice_path(@notice.id) %>
          <%= link_to "削除", doctors_notice_path(@notice.id), method: :delete %>
          <%= link_to "記事一覧", doctors_notices_path %>
      </div>
    </div>
    <div class="sidebar-right"></div>
  </div>
</div>

app/views/doctors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/homes/home.html.erb
<div class="home-container">
  <div class="home-image-container">
    <div id="slider">
      <div class="home-image"><img class="home-image-item" src="assets/home/home-imege1.jpg"></div>
      <div class="home-image"><img class="home-image-item" src="assets/home/home-image2.jpg"></div>
      <div class="home-image"><img class="home-image-item" src="assets/home/home-image3.jpg"></div>
    </div>
  </div>
  <div class="home-flame-top"></div>
  <img class="home-image-logo" src="assets/home/home-image-logo.PNG">
  
  <div class="home-main">
    <!-- お知らせ -->
    <div class="notise-container">
      <h3 class="notise-heading"><i class="fas fa-dog"></i> お知らせ</h3>
      <table>
        <% @notice.each do |notice| %>
        <tr class="notise-item">
          <td class="notise-item">
            <%= link_to notice.title, notice_path(notice.id) %>
          </td>
        </tr>
        <tr>
          <td class="notise-item">
            <%= notice.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </td>
        </tr>  
        <% end %>
      </table>
    </div>
    <!-- メニュー -->
    <div class="nav-container">
      <div class="nav-image btn-hover"><%= link_to notices_path do %><img class="nav-image-item" src="assets/item/nav-image-1.png"></img><% end %></div>
      <div class="nav-image btn-hover"><a href="http://ebc50th.com/t/shisetsu/"><img class="nav-image-item" src="assets/item/nav-image-2.png"></img></a></div>
      <div class="nav-image btn-hover "><a href="http://ebc50th.com/t/yokohama_rabbit_ct/"><img class="nav-image-item" src="assets/item/nav-image-3.png"></img></a></div>
      <div class="nav-image btn-hover"><a href="http://ebc50th.com/t/kenkoucheck/"><img class="nav-image-item" src="assets/item/nav-image-4.png"></img></a></div>
      <div class="nav-image btn-hover"><a href="http://ebc50th.com/t/staff/"><img class="nav-image-item" src="assets/item/nav-image-5.png"></img></a></div>
      <div class="nav-image btn-hover"><a href="http://ebc50th.com/t/shukkinhyou/"><img class="nav-image-item" src="assets/item/nav-image-6.png"></img></a></div>
      <div class="nav-image btn-hover"><%= link_to trimming_path, "data-turbolinks": false do %><img class="nav-image-item" src="assets/item/nav-image-7.png"></img><% end %></div>
    </div>
    <!-- ここまで -->
  </div>
  
  <div class="home-main container">
    <div class="box">
      <div class="inpuiry-containers">
        <div id="inpuiry-heading">
          <h2><i class="fas fa-paw" ></i> お問い合わせ・ご予約はコチラ <i class="fas fa-paw"></i></h2>
        </div>
        
        <!-- 電話・ネット予約ボタン -->
        <div class="inpuiry-container">
            <div class="inpuiry-image-1"></div>
            <div class="inpuiry-image">
              <a href="#"><img class="inpuiry-image-item btn-hover" src="assets/item/inpuiry-1.png"></a>
              <a href="http://ebc50th.com/t/wanchannekochan/"><img class="inpuiry-image-item btn-hover" src="assets/item/inpuiry-3.png"></a>
            </div>
            <div class="inpuiry-image">
              <a href="#"><img class="inpuiry-image-item btn-hover" src="assets/item/inpuiry-2.png"></a>
              <a href="http://ebc50th.com/t/usagisan/"><img class="inpuiry-image-item btn-hover" src="assets/item/inpuiry-3.png"></a>
            </div>
            <div class="inpuiry-image-2"></div>
        </div>
        <!-- ここまで -->
        
      </div>  
      <div class="calender">
        <img class="calender-image-item" src="assets/item/calender.png">
      </div>
      
      <h2 class="access-heading"><i class="fas fa-dove"></i> アクセス</h2>
      <div class="access-container">
        <div class="access-image">
          
          <!-- mapが入る -->
          <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQwSlLYlT8BEAuwBUaBhs5dkjJPf8XW4c&callback=initMap">
          </script>
          <script>
            function initMap() {
              var mapPosition = new google.maps.LatLng( 35.6882495,139.6856557 );//緯度経度
              var map = new google.maps.Map(document.getElementById("gmap"), {
              zoom: 17,//ズーム
              center: mapPosition
            });
              var marker = new google.maps.Marker({
              position: mapPosition,
              map: map
              });
            }
          </script>
          <div id="gmap"></div>
          <!-- ここまで　-->
          
        </div>
        <div class="access-text-container">
          <div class="access-text-heading">【交通案内】</div>
          <div class="access-text-item">
            <p>
              ○バスでお越しの方<br />
              青葉台駅より〇番のりばから東急バス「藤が丘駅行」乗車「桜台」下車  徒歩５分
            </p>
            <p>
              ○車でお越しの方<br />
              駐車場２台有り
            </p>
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/homes/hotel.html.erb
<div class="flame-top"></div>
<h1>ホテル</h1>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    
    <!-- ホテル詳細 -->
    <div class="box">
      <h2>ホテルの料金一覧</h2>
      <img class="prise-image" src="assets/hotel/price-hotel.png"></img>
      <div class="hotel-praice-text">
      <br>  
        <p>
          ※半日のお預かりは1泊2日料金の半額<br />
          例：トイプードルのワンちゃん
          朝10時から夕方6時までお預かり＝1,500円
        </p>
        <p>
          ※ご予約は<%= link_to"お電話のみ", root_path(anchor: "inpuiry-heading"), "data-turbolinks": false %>で承っております！
        </p>
      </div>
      <div class="containers">
        <img class="hotel-image3" src="assets/hotel/hotel-image3.PNG">
        <div class="message-container-h">
          <h4 class="message-heading-h">必ずご確認ください！</h4>
          <h5>■ 初めてワンちゃんホテルご利用の方へお願い</h5>
          <p>一年以内の混合ワクチン接種・狂犬病ワクチン接種の確認が必要です。</p>
          <h5>■ 初めてのホテルご利用の皆さまへお願い</h5>
          <p>普段食べているドッグフードや好物を一食分づつ小分けにして回数分ご持参下さい。</p>
        </div>
      </div>
    </div>
    
    <!-- ホテル設備紹介 -->
    <div class="box">
      <div class="commitment-text">
        <h3 class="commitment-heading hotel-commitment">当院のこだわり</h3>
        <ul>
          <li class="hotel-commitment-list"><i class="fas fa-paw" ></i> わんちゃん、ネコちゃん、ウサギさんの部屋ごとに分かれていてとても静かです</li>
          <li class="hotel-commitment-list"><i class="fas fa-paw" ></i> 獣医師によるチェックを行い、お帰りにホテルの報告書をお渡ししています</li>
          <li class="hotel-commitment-list"><i class="fas fa-paw" ></i> ドッグラン、ラビットランがあり、ストレスを解消できます</li>
        </ul>
      </div>
      <div class="hotel-background">
        <h2>設備のご紹介</h2>
        <div class="containers">
          <div class="hotel-item">
            <div class="hotel-image-heading">ワンちゃん・ねこちゃんのホテル</div>
            <img class="hotel-image-item" src="assets/hotel/hotel-image1.jpg">
          </div>
          <div class="hotel-item">
            <div class="hotel-image-heading">ウサギさんのホテル</div>
            <img class="hotel-image-item" src="assets/hotel/hotel-image2.jpg">
          </div>
        </div>
        <div class="hotel-image-heading">ドッグラン</div>
        <iframe width="100%" height="500" src="https://www.youtube.com/embed/lGxp8VApZOc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="dogrun-video"></iframe>
      </div> 
    </div>
    <!-- ここまで -->
    
  </div>  
  <div class="sidebar-right"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>可愛動物病院</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application" %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>
  <body>
    <header>
      <div class="header-container">
        <div class="headlign">
          <%= link_to root_path, "data-turbolinks": false do %><div class="logo"></div><% end %>
          <div class="header-item">
            <%= link_to root_path(anchor: "inpuiry-heading"), "data-turbolinks": false do %>
              <div class="reservation-image"></div>
            <% end %>
          </div>  
        </div>
      </div>
      <nav class="menubar">
        <ul>
          <% if doctor_signed_in? %>
            <li><%= link_to "サインアウト", destroy_doctor_session_path, method: :delete %></li>
            <li><%= link_to "記事投稿", new_notice_path %></li>

          <% else %>
            <li><a href="http://ebc50th.com/t/shinsatsuananai/">診療方針</a></li>
            <li><a href="http://ebc50th.com/t/staff/">スタッフ紹介</a></li>
            <li><%= link_to"トリミング",trimming_path, "data-turbolinks": false  %></li>
            <li><%= link_to"ホテル", hotel_path %></li>
            <li><%= link_to"施設", information_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>  
    <main>
        <%= yield %>
    </main>
    
    <footer>
      <div class="flame-bottom"></div>
      <div class="footlign">
      管理者の方は<%= link_to "コチラ>>", new_doctor_session_path %>
        <p class="copyright">Copyright © </p>
      </div>
    </footer>
  </body>
</html>

app/views/notices/edit.html.erb
<div class="flame-top"></div>
<h1>記事投稿</h1>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    <div class="box">
      <%= form_with model: @notice, local: true do |f| %>
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title %>
      <%= f.label :body, "内容" %>
      <%= f.text_area :body %>
      <%= f.label :body, "カテゴリ" %>
      <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]} %>
      <%= f.submit "投稿" %>
      <% end %>
      
    </div>
  </div>
  <div class="sidebar-right"></div>
</div>  

app/views/notices/show.html.erb
<div class="flame-top"></div>
<div class="containers">
  <div class="sidebar-left"></div>
  <div class="main-container">
    <div class="box">
      <table>
        <thead>
          <tr>
            <th>タイトル</th>
            <th>画像</th>
            <th>内容</th>
            <th>カテゴリー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @notice.title %>
            </td>
            <td>
              <% @notice.images.each do |image| %>
                <%= image_tag image.to_s %>
              <% end %>  
            </td>
            <td>
              <%= @notice.body %>
            </td>
            <td>
              <%= @notice.category.name %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= link_to "編集", edit_notice_path(@notice.id) %>
    </div>
  </div>
  <div class="sidebar-right"></div>
</div>  